apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "simple-kubernetes-webhook.acme.com"
webhooks:
  - name: "simple-kubernetes-webhook.acme.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: simple-kubernetes-webhook
        path: /mutate-pods
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaRENDQWt5Z0F3SUJBZ0lVSHlQUVc0N0ZTVDFKRFhUT1pmejF2Z1Naa2JRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URUxNQWtHQTFVRUJoTUNRVlV4SWpBZ0JnTlZCQU1NR1hOcGJYQnNaUzFyZFdKbGNtNWxkR1Z6TFhkbApZbWh2YjJzd0hoY05NalV3T1RBNU1USXdNelV3V2hjTk1qWXdPVEE1TVRJd016VXdXakF4TVFzd0NRWURWUVFHCkV3SkJWVEVpTUNBR0ExVUVBd3daYzJsdGNHeGxMV3QxWW1WeWJtVjBaWE10ZDJWaWFHOXZhekNDQVNJd0RRWUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSmt4WU1tMU9pc0s0V25IYUk5UlpLYnN2Ujl0NWVVZApIb0NDSTFLQnRLcm5kN05Gc0trVEFKMk5lQUs0a2l2RDVTdkZ6UGZXaXh1YXVBd2tZNWliWnFXYkZTck1xZ0lTCnB5WnFxS2YwY0FmSUVRYUZGZS8wckFwNURDNGFHSGE1QXN2T283cE5leDN2WWNUVnRwQURBZ1VnVWFrcFNDQnAKV2NiNm9uRnprdlVhdFpoRGlNcWFoaHNmbHIzTE1CUkt4VHkzVTgzT1lscHdzSmt3eUpYS1hJMzdkbEZ0QWZXQgpSMlg3ZUM3a0VMOWRNOFB5aDFoRDVXSkoxUEZ4bVdpYndRSXNOT002Q1Byd0d1UzltUTBjV0IvVXUxNzd4VFkyCjFBeTRoNVc3MStTYmZmcWVWeGV0b1pnQU9lT1dTSmlEZ2tjenF6bXNaLzJ1UzVhdGxrUjB0MGtDQXdFQUFhTjAKTUhJd01BWURWUjBSQkNrd0o0SWxjMmx0Y0d4bExXdDFZbVZ5Ym1WMFpYTXRkMlZpYUc5dmF5NWtaV1poZFd4MApMbk4yWXpBZEJnTlZIUTRFRmdRVSs4UHcwTHQrMVRmaEJBYnZGREdEY1FrVlFUWXdId1lEVlIwakJCZ3dGb0FVCk1uM3diZXBCek8rdERJbGpTNXZuQnV1bWJKNHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRk42M2MvNWxHWkEKZFFINXpMYWRZWnRWL1l2T2R2NVhHYzlOOUo4NjhJMmhvOVU0NTRUNmRvYTlEbHpSVnhFTjQ2RVc2RFVJc1RDcApvaHcwYTFqSk52WHRmOGNDcXBZdlpJdFNpd0NqU2pLM0prMWtlOWVSUlNaY0hZckRmeEdQVjJFRk14SGlmOFFaCldEaVJ6QzJIZnNOMDdkQmxsaTZRY1NZSzlQL0xNWEovbElzOVM4ek1qQmdUdUxJWDJqV2J3MzZlamU5dnZxcXgKMDNDMmtWUU1zeHlwZkdodThZZWNDVkV5QnpDbWI2bGNzYytZZHlzZE10SnVOSFk5dVZvc0dmSDlwOUt1UnU4cwpueko4VXZUemVSdjkwZ21yVGFveHo4QlJXNENOVWRJamZZL0ZGV3p4RkxMVVA0QnYzby91WHBZQWdlMVZ6T3l4Cm0veS8waTNtcGRjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
